### ISSUE TITLE
Allow users to specify the identifier of the CA certificate for the DB instance.

### ISSUE THREAD

**Issue by rickardl** [telia-oss/terraform-aws-rds-instance#20]
### Feature request

> How can we improve the module?

The current SSL/TLS certificates for RDS DB instances will expire on March 5, 2020 as part of standard maintenance and security best practices for RDS. 

Amazon recommends changing the identifier after February 2020

```
aws rds modify-db-instance --db-instance-identifier <db_instance_identifier> --ca-certificate-identifier rds-ca-2019
```

This should be offered through our module, by exposing `ca_cert_identifier` that specifies the identifier of the CA certificate for the DB instance.

Additionally, any new RDS DB instances and Aurora DB clusters created after January 14, 2020 will have the new certificates, which makes this change necessary.

**Comment by itsdalmo** [comment]
I'm not sure about the behaviour here either. But since it's an optional value I assume it will just use the same defaults as if you launched it in the console, which to me means that it will be automatically rotated by Amazon. I might be wrong, but we won't know without actually testing it - or waiting for someone to report that they tried it and had a problem? 🤷‍♂
